language: node_js
node_js:
  - v8

before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org

script: echo "npm test temporarily disabled"

deploy:
  provider: npm
  email: "maordavidov@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: false